################################################################################
# SETUP
################################################################################
# Modules
from os.path import join

# Configuration

# Directories
SRC_DIR = '../src'
SIGNATURES_DIR = 'signatures'
MUTATIONS_DIR = 'mutations'

RAW_MUTATIONS_DIR = join(MUTATIONS_DIR, 'raw')

# Files
RAW_COSMIC_SIGNATURES = join(SIGNATURES_DIR, 'cosmic_signatures_probabilities.txt')
COSMIC_SIGNATURES = join(SIGNATURES_DIR, 'cosmic-signatures.tsv')

ICGC_R22_BRCA_MUTATIONS = join(RAW_MUTATIONS_DIR, 'ICGC-BRCA-EU.RELEASE_22.SBS.tsv')
ICGC_R22_BRCA_MUTATIONS_RENAMED = join(RAW_MUTATIONS_DIR, 'ICGC-BRCA-EU.RELEASE_22.SBS.renamed.tsv')
ICGC_R22_BRCA_MUTATIONS_JSON = join(MUTATIONS_DIR, 'ICGC-BRCA-EU.RELEASE_22.SBS.renamed.sigma.json')
ICGC_R22_BRCA_SAMPLE_FILE = join(RAW_MUTATIONS_DIR, 'sample.r22.BRCA-EU.tsv')

PROCESS_COSMIC_SIGNATURES_PY = join(SRC_DIR, 'process_cosmic_signatures.py')
PROCESS_MUTATIONS_FOR_SIGMA_PY = join(SRC_DIR, 'process_mutations_for_sigma.py')
CONVERT_PATIENT_NAMES_PY = join(SRC_DIR, 'convert_patient_names.py')

################################################################################
# RULES
################################################################################
# General
rule all:
    input:
        ICGC_R22_BRCA_MUTATIONS_JSON

# Download processed ICGC BRCA (release 22) BRCA mutations, convert into JSON
# format
rule convert_mutations_to_json:
    input:
        mutations=ICGC_R22_BRCA_MUTATIONS_RENAMED,
        signatures=COSMIC_SIGNATURES
    output:
        ICGC_R22_BRCA_MUTATIONS_JSON
    shell:
        'python {PROCESS_MUTATIONS_FOR_SIGMA_PY} -mf {input.mutations} '\
        '-sf {input.signatures} -o {output}'

rule convert_patient_names:
    input:
        mutations=ICGC_R22_BRCA_MUTATIONS,
        samples=ICGC_R22_BRCA_SAMPLE_FILE
    output:
        ICGC_R22_BRCA_MUTATIONS_RENAMED
    shell:
        'python {CONVERT_PATIENT_NAMES_PY} -mf {input.mutations} -sf {input.samples} '\
        '-o {output}'
        
rule download_icgc_r22_brca_mutations:
    params:
        url='https://obj.umiacs.umd.edu/mutation-signature-explorer/mutations/ICGC/processed/extended/extended.ICGC-BRCA-EU.RELEASE_22.SBS.tsv'
    output:
        ICGC_R22_BRCA_MUTATIONS
    shell:
        'wget -O {output} {params.url}'

rule download_sample_mapping:
    params:
        url='https://dcc.icgc.org/api/v1/download?fn=/release_22/Projects/BRCA-EU/sample.BRCA-EU.tsv.gz'
    output:
        ICGC_R22_BRCA_SAMPLE_FILE
    shell:
        'wget -O - {params.url} | gunzip -c > {output}'
        
# Download and process COSMIC signatures
rule process_cosmic_signatures:
    input:
        RAW_COSMIC_SIGNATURES
    output:
        COSMIC_SIGNATURES
    shell:
        'python {PROCESS_COSMIC_SIGNATURES_PY} -i {input} -o {output}'
        
rule download_cosmic_signatures:
    params:
        url='http://cancer.sanger.ac.uk/cancergenome/assets/signatures_probabilities.txt'
    output:
        RAW_COSMIC_SIGNATURES
    shell:
        'wget -O {output} {params.url}'
